// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.SUPABASE_URL || "https://chsbyichnwplwdgplsfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoc2J5aWNobndwbHdkZ3Bsc2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MjQ5MTEsImV4cCI6MjA1NTUwMDkxMX0.Ke9-9iLB9ZjXMn6JP6WWVq7A_UI7Dpzg3KKkrskBxWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);